lsコマンドを作る
asahifuke/ruby-practices pull request #5
Opened 2022-06-17 06:02 UTC by asahifuke

2022-06-19 15:14 UTC, u1tnk requested changes
Listのinitializeの責務が大き過ぎそうではありますが、lsのオブジェクト版では無いので十分と思います。
detach/atachはメソッド名が内容と合っていないので修正お願いします 🙏

2022-06-19 15:14 UTC, u1tnk commented on 05.ls/lib/ls.rb
> +  def detach
detach/atach というと何かを変数などに入れたり出したりする印象ですが、実際detachは列ごとにファイルを格納しているし、atachは出力用にデータを整形して文字列にしているようです。
適切なメソッド名にしましょう。

また、今のinitializeと処理の分け方からすると detachの内容までinitializeでatachのみ(となるとshowだけになりそうです)呼び出し時に実行で良さそうです。

2022-06-20 04:41 UTC, asahifuke commented on 05.ls/lib/ls.rb
> +  def detach
質問がありますが、
なぜ、今のinitializeと処理の分け方からするとdetachの内容までinitializeでatachのみ呼び出し時に実行で良さそうなのでしょうか？
また、どのような場合、detachとatachの内容を分けた方が良い（または二つとも合わせる方）のでしょうか

2022-06-20 08:21 UTC, u1tnk commented on 05.ls/lib/ls.rb
> +  def detach
> なぜ、今のinitializeと処理の分け方からするとdetachの内容までinitializeでatachのみ呼び出し時に実行で良さそうなのでしょうか？

現状のinitializeの内容を見ると、初期処理は全部行っていて、detachまでは処理をしやすくするデータの配置、整理で、atachは他の処理に再利用できないレベルの処理になっていたので分類的にatachだけ性格が違っていたのでdetachのinitializeへの移動を提案しました。
ここは絶対的な正解があるわけでは無く、他の分け方もあると思いますが、detachだけ他の方針と合っていないように見えたという事です。

> また、どのような場合、detachとatachの内容を分けた方が良い（または二つとも合わせる方）のでしょうか？

メソッドの粒度という事でしょうか？
でしたら、どちらが良いか言うと分けた方が良いと思います。そこまで長く無いので一緒になっていても指摘するかどうかは微妙ですが、今回は元々別れていて、性格が違うと思ったので指摘しました。
また、今回は旧detachはそのまま内容をinitializeに移動して頂きましたが、名前を変えて、内容はそのままでinitializeから呼び出す方法もあります。

2022-07-10 03:08 UTC, u1tnk approved these changes

2022-07-10 03:08 UTC, u1tnk commented on 05.ls/lib/list.rb
> +    files_directories.reverse! if is_reverse
reverseだけ渡されてくるので分かりやすいですね 👍

2022-07-12 14:15 UTC, merged